#!/usr/bin/env python3
"""Derive a census of every AF-R-### rule the build cites.

NOT the rules index — see the header it writes. This reads the shipped
single-file build and reports, per rule: how many times it is cited, whether
any citation is a machine-enforced refusal, and the message that refusal
carries. Its job is to make "cited but not indexed" measurable, which it has
not been since 0.9.3.

    python3 tools/rules-census.py aetherfall.html docs/RULES_CITED_<ver>.md
"""
import re, sys, collections

def census(path):
    src = open(path, encoding="utf-8").read()
    ver = (re.search(r'version:\s*"([\d.]+)"', src) or [None, "?"])[1]
    cites = collections.defaultdict(list)
    for i, ln in enumerate(src.split("\n"), 1):
        if len(ln) > 4000:                      # embedded data URI, not code
            continue
        for m in re.finditer(r"AF-R-(\d+)", ln):
            rid, num = "AF-R-" + m.group(1), m.group(1)
            #  A refusal reads: rules.refuse("AF-R-###", <message expression>)
            ref = re.search(r'rules\.(?:refuse|require|forbid)\(\s*["\']AF-R-%s["\']\s*,\s*(.+)$' % num, ln)
            if ref:
                msg = ref.group(1).rstrip()
                msg = re.sub(r'\)\s*;?\s*$', '', msg).strip().strip('`"\'')
                cites[rid].append((i, "ENFORCED", msg))
            else:
                txt = ln.strip(); j = txt.find("AF-R-")
                cites[rid].append((i, "cited", re.sub(r"\s+", " ", txt[max(0, j-70):j+110]).strip()))
    return ver, cites

def render(ver, cites):
    key = lambda r: int(r.split("-")[-1])
    rules = sorted(cites, key=key)
    enforced = {r for r in rules if any(k == "ENFORCED" for _, k, _ in cites[r])}
    total = sum(len(v) for v in cites.values())
    esc = lambda s: s.replace("|", "\\|")[:150]
    o = [f"# Rules cited in the source — derived census at {ver}\n\n",
         "> **This is NOT the rules index.** `docs/RULES_INDEX.md` has never existed\n"
         "> in this repository, and two addendum files amend an index that is not\n"
         "> here. This document is *derived from the build*: every `AF-R-###` the\n"
         "> code actually cites, with where and how. It cannot say what a rule\n"
         "> MEANS, or whether it is LOCKED or FLEXIBLE — only the Bible can, and\n"
         "> the Bible is not in the repo.\n>\n"
         "> Its one job is to make the gap measurable. Until now, \"cited but not\n"
         "> indexed\" and \"indexed but not cited\" were both unanswerable. Half of\n"
         "> that is answered below; supply the index and the other half follows.\n\n",
         f"**{len(rules)} distinct rules**, **{total} citations**, "
         f"**{len(enforced)} machine-enforced** — those appear in an\n"
         "`AF.rules.refuse/require/forbid` call, so breaking them stops the build or\n"
         "refuses the action. The other "
         f"{len(rules) - len(enforced)} are cited in reasoning only: nothing fails\n"
         "when the code drifts from them, which makes them the ones worth reading\n"
         "against the Bible first.\n\n",
         "## Enforced — a refusal fires\n\n| rule | cites | what the refusal says |\n|---|---|---|\n"]
    for r in rules:
        if r not in enforced: continue
        msg = next(t for _, k, t in cites[r] if k == "ENFORCED")
        o.append(f"| `{r}` | {len(cites[r])} | {esc(msg)} |\n")
    o.append("\n## Cited in reasoning only — no machine check\n\n"
             "| rule | cites | where it is first invoked |\n|---|---|---|\n")
    for r in rules:
        if r in enforced: continue
        ln, _, txt = cites[r][0]
        o.append(f"| `{r}` | {len(cites[r])} | L{ln}: …{esc(txt)}… |\n")
    o.append(f"\n---\n\nGenerated by `tools/rules-census.py` from `aetherfall.html` at {ver}.\n")
    return "".join(o)

if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "aetherfall.html"
    ver, cites = census(src)
    out = sys.argv[2] if len(sys.argv) > 2 else f"docs/RULES_CITED_{ver.replace('.','_')}.md"
    open(out, "w", encoding="utf-8").write(render(ver, cites))
    print(f"{out}: {len(cites)} rules, {sum(len(v) for v in cites.values())} citations")
